name: 'Test Report'
on:
  workflow_run:
    workflows: [terratest]              # runs after test workflow
    types:
      - completed
jobs:
  report:
    runs-on: general-purpose
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results            # artifact name
        name: Test Results                # Name of the check run which will be created
        path: '*.xml'                     # Path to test results (inside artifact .zip)
        reporter: java-junit              # Format of test results
